version: '3'
services:

  postgres:
    container_name: postgres-auth-google
    image: postgres
    environment:
      POSTGRES_DB: zup_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "55491:5432"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
    extra_hosts:
    - "moby:127.0.0.1"
