version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: op_events
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
    - "55491:5432"
    restart: always