spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:55491/op_events
    username: postgres
    password: postgres
  #JPA Properties
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  kafka:
    brokers: 0.0.0.0:2181 #kafkahost:kafkaport
    producer:
      #bootstrapAddress: 0.0.0.0:2181
      bootstrap-servers: 0.0.0.0:9092

