spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:55491/op_events
    username: postgres
    password: postgres
  #JPA Properties
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092

    bootstrap-servers: localhost:9092

