spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:55491/op_events
    username: postgres
    password: postgres
  #JPA Properties
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  kafka:
    consumer:
      bootstrap.servers: "localhost:29092"
      key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    #brokers: 0.0.0.0:2181 #kafkahost:kafkaport
    producer:
      bootstrap-servers: 0.0.0.0:9092