INSERT INTO topic(name) VALUES('TOPICNAME-1');
INSERT INTO topic(name) VALUES('TOPICNAME-2');
INSERT INTO topic(name) VALUES('TOPICNAME-3');
INSERT INTO topic(name) VALUES('TOPICNAME-4');
INSERT INTO topic(name) VALUES('TOPICNAME-5');
INSERT INTO topic(name) VALUES('TOPICNAME-6');